apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-deployment
  namespace: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad
  template:
    metadata:
      labels:
        app: bad
    spec:
      volumes:
        - name: host
          hostPath:
            path: /var/run
      containers:
        - name: app
          image: busybox:1.36
          command: ["sh","-lc","sleep 3600"]
          securityContext:
            privileged: true
