apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-deployment
  namespace: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: good
  template:
    metadata:
      labels:
        app: good
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: app
          image: busybox:1.36
          command: ["sh","-lc","sleep 3600"]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
